[window]
dynamic_padding = false
padding = { x = 8, y = 8 }
decorations = "None"
opacity = 0.77
blur = true
startup_mode = "Fullscreen"
title = "~The Commits will flow~"
dynamic_title = true
decorations_theme_variant = "None"
