[window]
dynamic_padding = false
padding = { x = 8, y = 8 }
decorations = "None"
position = { x = 80, y = 80 }
opacity = 0.66
blur = true
startup_mode = "Windowed"
title = "~The Commits will flow~"
dynamic_title = true
decorations_theme_variant = "None"
