---
  - name: "Install latest packages from packages.txt"
    become: True
    ansible.builtin.package:
      name:
        - "{{ item }}"
      state: latest
    with_lines: "cat {{ ansible_pkg_mgr }}/packages.txt"
